name: Merge Main
on:
  push:
    branches:
      - main
jobs:
  make-coverage:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - run: make install
      - run: make test
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
  release:
    needs: make-coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          prerelease: true
          generateReleaseNotes: true
          tag: ${{ steps.version.outputs.version }}
