name: Merge Main
on:
  push:
    branches:
      - main
jobs:
  make-coverage:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - run: make install
      - run: make test
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - run: make install
      - name: Build UI Docs
        run: make build-ui-docs
      - name: Build API Docs
        run: make build-api-docs
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
            docs
            storybook-static
  build-pages-artifact:
    needs:
      - build-docs
      - make-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: compiled
      - uses: actions/download-artifact@v3
        with:
          name: coverage
          path: coverage
      - shell: bash
        run: |
          mv compiled/docs docs
          mv compiled/storybook-static docs/storybook
          mv coverage/lcov-report docs/coverage
          rm -rf compiled coverage
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/
  deploy:
    needs: build-pages-artifact
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
  release:
    needs: make-coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          prerelease: true
          generateReleaseNotes: true
          tag: ${{ steps.version.outputs.version }}
