# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

env:
  IMAGE_NAME: gxldcptrick/zombie-nomnom-ui:${{ github.event.release.tag_name }}
  LATEST_IMAGE_NAME: gxldcptrick/zombie-nomnom-ui:latest

permissions:
  contents: read

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: deploy
          tags: |
            ${{ env.IMAGE_NAME }}
            ${{ env.LATEST_IMAGE_NAME }}
          build-args: |
            PDM_BUILD_SCM_VERSION=${{ github.event.release.tag_name }}
  update-changelog:
    runs-on: ubuntu-latest
    needs: publish-docker
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "✏️ Generate release changelog"
        id: changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          excludeTagsRegex: '^(\d+.){2}\d+-main.+$'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): Update Changelog for ${{ github.event.release.tag_name }}"
          branch: main
          commit_user_name: Bender
