name: Test Branch
on:
  pull_request:
    branches:
      - main
jobs:
  make-coverage:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - run: make install
      - run: make test
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@v1
